repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.9
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/guilatrova/tryceratops
  rev: v2.4.1
  hooks:
    - id: tryceratops